function writeBonifico(){
    document.getElementById('writeHere').innerHTML = "<br><br><form method=\"post\"><table  class=\"movementTable\"><tr><td colspan=\"2\"><h3 name=\"bonifico\" value=\"bonifico\">BONIFICO:</h3></td></tr><tr><td><label for=\"IBAN1\">IBANbeneficiario</label></td><td><input type=\"text\" step=\"0.01\" id=\"IBAN1\" name=\"IBAN1\" placeholder=\"IBAN beneficiario\"></td></tr><tr><td><label for=\"causale\">CAUSALE:</label></td><td><textArea maxlength=\"180\"  cols=\"50\" rows=\"6\" wrap=\"hard\" name=\"causale\">causale</textarea></td></tr><tr><td><label for=\"importo\">importo</label></td><td><input type=\"number\" id=\"importo\" name=\"importo\" placeholder=\"importo\" min=\"0\"></td></tr><tr><td colspan=\"2\"><input type=\"submit\" class=\"insertM_button\" name=\"insBonifico\" id=\"insBonifico\" value=\"INSERT MOVEMENT\"></td></tr></table></form><br><br>   ";
}
function writeVersamento(){
    document.getElementById('writeHere').innerHTML = "<br><br><form method=\"post\"><table  class=\"movementTable\"><tr><td colspan=\"2\"><h3 name=\"versamento\" value=\"versamento\">VERSAMENTO:</h3></td></tr><tr><td><label for=\"IBAN1\">IBANbeneficiario</label></td><td><input type=\"text\" step=\"0.01\" id=\"IBAN1\" name=\"IBAN1\" placeholder=\"IBAN beneficiario\"></td></tr><tr><td><label for=\"causale\">CAUSALE:</label></td><td><textArea maxlength=\"180\"  cols=\"50\" rows=\"6\" wrap=\"hard\" name=\"causale\">causale</textarea></td></tr><tr><td><label for=\"importo\">importo</label></td><td><input type=\"number\" id=\"importo\" name=\"importo\" placeholder=\"importo\" min=\"0\"></td></tr><tr><td colspan=\"2\"><input type=\"submit\" class=\"insertM_button\" name=\"insVersamento\" id=\"insVersamento\" value=\"INSERT MOVEMENT\"></td></tr></table></form><br><br>   ";
}
function writePrelevamento(){
    document.getElementById('writeHere').innerHTML = " <br><br><form method=\"post\"><table  class=\"movementTable\"><tr><td><label for=\"importo\">Importo da prelevare:</label></td><td><input type=\"number\" id=\"importo\" name=\"importo\" placeholder=\"importo\" min=\"0\"></td></tr><tr><td colspan=\"2\"><input type=\"submit\" class=\"insertM_button\" name=\"insPrelevamento\" id=\"insPrelevamento\" value=\"INSERT MOVEMENT\"></</td></tr></table></form><br><br>   ";
}
function writeImposta(){
    document.getElementById('writeHere').innerHTML = " <h2>POLICY AZIENDALE RIGUARDO L'IMPOSTA DI BOLLO SUL CONTOCORRENTE</h2><br><h2>Nel caso di estratti di conto corrente bancario e postale e di rendiconti dei libretti di risparmio bancari e postali, l’imposta che si applica è pari a:34,20 euro per le persone fisiche;100,00 euro per i soggetti diversi dalle persone fisiche (ad esempio società, associazioni)L’imposta viene applicata al momento dell’emissione dell’estratto conto o del rendiconto ed è relativa al periodo rendicontato anche in caso di apertura e chiusura in corso d’anno.Nel caso di assenza di rendiconto nell’anno, l’imposta è applicata al 31 dicembre di ciascun anno. Nel caso in cui lo stesso cliente intrattenga più rapporti di conto corrente e/o risulti intestatario di più libretti di risparmio, l’imposta annua deve essere corrisposta per ciascun rapporto.</h2 ><br>";
}
function home(){
    document.getElementById('writeHere').innerHTML = " ";
}